### ISSUE TITLE
Branch name is invalid

### ISSUE THREAD

**Issue by zgunz42** [extraStatic/stapsher#2]
**Response json**
```json
{
"code": "SERVER_PROBLEM",
"info": "StatusCodeError: 400 - {\"message\":\"Branch name is invalid\"}"
}
```
**Base URL**
gitlab/**-dev/**-site/master/comment/new

**Comment by MunifTanjim** [comment]
What's in your `stapsher.yaml` file?

**Comment by zgunz42** [comment]
```yaml
comment:
  akismet:
    enable: true
    apiKey: secret
    siteUrl: https://example.com
  recaptcha:
    enable: true
    secretKey: secret
  allowedFields: ["author","comment","email","site"]
  branch: master
  commitMessage: "add new comment by {fields.author} <Stapsher>"
  filename: "{_date~unix}.{_id}"
  path: "data/comments/{options.uid}"
  format: yaml
  generatedFields:
    timestamp:
      type: date
      options:
        format: unix
  moderation: true
  requiredFields: ["author","comment","email"]
  transforms:
    email: "hash~md5"
```

I also check akismet  on `https://stapsher.extrastatic.xyz/gitlab/some-user/some-repo/master/comment/verify/akismet`
and i got response like this
```json
{
"enabled": true,
"validAPIKey": true
}
```
